### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by PhilipNelson5** [PhilipNelson5/SpaceCowboys#3]
**Existing users**
  - [x] Username and password fields
  - [x] Confirm username and password with server
  - [x] disallow empty fields
  - [x] alert user when login fails

**New user**
  - [x] Username and 2 password fields
  - [x] check passwords match
  - [x] register passwords with server
  - [x] disallow empty fields
  - [x] alert user when user creation fails fails

**TODO**
- [x] make CREATE_USER_REQUEST use promise model
- [x] clean up login.registerNewUser function
